### ISSUE TITLE
Improvements on the current report

### ISSUE THREAD

**Issue by billlyzhaoyh** [AIforGoodSimulator/compartmental-model#14]
#TODO:

- [ ] 1. Add percentages to the cumulative cases to signify what is the proportion of people getting something

- [ ] 2. Add asymptomatic infections count to the table

- [ ] 3. When the case number is reduced to 0 adjust the peak day not to be negative

- [ ] 4. Need to adjust the hospitalisation and critical person days for the interventions that will naturally prolong it (for example by increasing the hospital capacity
